---
title: "Mendel's First Law"
author: "Orr Shomroni"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

## Problem

`r text_spec("Probability", color = "#0088cc", bold=T)` is the mathematical study of randomly occurring phenomena. We will model such a phenomenon with a `r text_spec("random variable", color = "#0088cc", bold=T)`, which is simply a variable that can take a number of different distinct `r text_spec("outcomes", color = "#0088cc", bold=T)` depending on the result of an underlying random process.

For example, say that we have a bag containing 3 red balls and 2 blue balls. If we let _X_ represent the random variable corresponding to the color of a drawn ball, then the `r text_spec("probability", color = "#0088cc", bold=T)` of each of the two outcomes is given by $Pr(X=red)=\frac{3}{5}$ and $Pr(X=blue)=\frac{2}{5}$.

Random variables can be combined to yield new random variables. Returning to the ball example, let _Y_ model the color of a second ball drawn from the bag (without replacing the first ball). The probability of _Y_ being red depends on whether the first ball was red or blue. To represent all outcomes of _X_ and _Y_, we therefore use a `r text_spec("probability tree diagram", color = "#0088cc", bold=T)`. This branching diagram represents all possible individual probabilities for _X_ and _Y_, with outcomes at the endpoints ("leaves") of the tree. The probability of any outcome is given by the product of probabilities along the path from the beginning of the tree; see `r text_spec("Figure 2", color = "#0088cc", bold=T)` for an illustrative example.

An `r text_spec("event", color = "#0088cc", bold=T)` is simply a collection of outcomes. Because outcomes are distinct, the probability of an event can be written as the sum of the probabilities of its constituent outcomes. For our colored ball example, let _A_ be the event "_Y_ is blue." Pr(_A_) is equal to the sum of the probabilities of two different outcomes: Pr(_X_=blue and _Y_=blue)+Pr(_X_=red and _Y_=blue), or $\frac{3}{10}+\frac{1}{10}=\frac{2}{5}$ (see Figure 2 above).

`r text_spec("Given", color = "#46a546", bold=T)`: Three positive integers _k_, _m_, and _n_, representing a population containing $k+m+n$ organisms: _k_ individuals are homozygous dominant for a factor, _m_ are heterozygous, and _n_ are homozygous recessive.

`r text_spec("Return", color = "#46a546", bold=T)`: The probability that two randomly selected mating organisms will produce an individual possessing a dominant allele (and thus displaying the dominant phenotype). Assume that any two organisms can mate.

## Sample Dataset

```
2 2 2
```

## Sample Output

```
0.78333
```

```{python}
def wrap(string):
    s=''
    for i in range(0,len(string),80):
        s+=string[i:i+80]
        s+='\n'
    return s
k=2
m=2
n=2


prob=0.78333
# string="The Hamming distance between string s "+s[0].replace("\n","")+" and string t "+s[1].replace("\n","")+ " is "+str(dH)
# print(wrap(string))
```
