---
title: "Rabbits and Recurrence Relations"
author: "Orr Shomroni"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80),tidy=TRUE)
```

## Problem

A `r text_spec("sequence", color = "#0088cc", bold=T)` is an ordered collection of objects (usually numbers), which are allowed to repeat. Sequences can be finite or infinite. Two examples are the finite sequence $(\pi, -\sqrt{2}, 0, \pi)$ and the infinite sequence of odd numbers (1,3,5,7,9,...). We use the notation $a_n$ to represent the _n_-th term of a sequence.

A `r text_spec("recurrence relation", color = "#0088cc", bold=T)` is a way of defining the terms of a sequence with respect to the values of previous terms. In the case of Fibonacci's rabbits from the introduction, any given month will contain the rabbits that were alive the previous month, plus any new offspring. A key observation is that the number of offspring in any month is equal to the number of rabbits that were alive two months prior. As a result, if _F_~n~ represents the number of rabbit pairs alive after the _n_-th month, then we obtain the `r text_spec("Fibonacci sequence", color = "#0088cc", bold=T)` having terms _F_~n~ that are defined by the recurrence relation $F_n=F_n-1+F_n-2$ (with $F_1=F_2=1$ to initiate the sequence). Although the sequence bears Fibonacci's name, it was known to Indian mathematicians over two millennia ago.

When finding the _n_-th term of a sequence defined by a recurrence relation, we can simply use the recurrence relation to generate terms for progressively larger values of n. This problem introduces us to the computational technique of `r text_spec("dynamic programming", color = "#0088cc", bold=T)`, which successively builds up solutions by using the answers to smaller cases.

`r text_spec("Given", color = "#46a546", bold=T)`: Positive integers $n\leq40$ and $k\leq5$.

`r text_spec("Return", color = "#46a546", bold=T)`: The total number of rabbit pairs that will be present after _n_ months, if we begin with 1 pair and in each generation, every pair of reproduction-age rabbits produces a litter of _k_ rabbit pairs (instead of only 1 pair).

## Sample Dataset

```
5 3
```

## Sample Output

```
19
```

```{python}
def fib(n, k):
  if n<0:
    print("Incorrect input")
  elif n==0:
    return 0
  elif n==1 or n==2:
    return 1
  else:
    return fib(n-1,k) + fib(n-2,k)*k
  
n=33
k=3
F=fib(n,k)
string="The total number of rabbit pairs present after "+str(n)+" months, with each adult\n"+"pair producing "+str(k)+" pairs of offsprings is "+str(F)
print(string)
```

